# Consent

Once the parent and child come into the lab, seat them in the rainbow room on the couch for consenting. 

Make some small talk - Ask the participant how they got here. If they have participated before in research. Offer them a bottle of water. Thank them for coming and for giving up their weekend to help science.

Tell the parent and child that the first thing you are going to do is go over all of the things they will do today, and have them sign the consent forms. 

Speak to them and direct them through the whole process. 

<h3>Things you will do in the lab</h3>

- Stick stickers on you to measure heart rate, sweat, stomach muscles.
- Sit with parent and talk about fun things and hard things (filming).
- Parent stays in room and answers more questions. 
- Child goes next door to play computer games (look at pictures, watch movies). Some of the movies and pictures will be a little bit scary, others sad, others boring. 
- One of the games involves a loud annoying noise, we will adjust it for you. 
- You will also do some other games on paper and pencil - like puzzle and word games
- You will answer some questionnaires
- We will also measure your height, weight, and waist circumference. 
- We will take three biological samples: 
    - Hair - stress hormones
    - Saliva - microbiome 
    - Blood - immune - wear goggles
- Do you get sick or dizzy when you see blood or hurt yourself? 
- If we need to, can we prick two fingers?
- When you are done with all of that, you will get a big prize, then we will pay you and you will go home. 
- You will get $45 for the work you put in today.

<h3>Things you will do at home</h3>

<h4>Child</h4>

- Poop sample - microbiome
- Stool scale
- Memory game - to see what you remember from lab.

<h4>Parent</h4>

- 24 hour food recall

When you complete the poop sample and the games at home, we will pay you another $20 in the form of a giftcard. 

<h3>Things to know</h3>
You are a volunteer, which means that you do not have to do anything, or say anything that makes you uncomfortable. We would like you to try everything you can, and to do your best, but if there are things you absolutely do not want to do, just tell us, that is o.k.

We keep your participation confidential - ID number. 

We want you to come in again in the future, so we will ask for some information so we can contact you in the future. 

*Sign consent/assent forms including DBS form and Contact Sheet*
