# Protocols

## Consent

Once the parent and child come into the lab, seat them in the rainbow room on the couch for consenting. 

Make some small talk - Ask the participant how they got here. If they have participated before in research. Offer them a bottle of water. Thank them for coming and for giving up their weekend to help science.

Tell the parent and child that the first thing you are going to do is go over all of the things they will do today, and have them sign the consent forms. 

Speak to them and direct them through the whole process. 

### Things you will do in the lab

- Stick stickers on you to measure heart rate, sweat, stomach muscles.
- Sit with parent and talk about fun things and hard things (filming).
- Parent stays in room and answers more questions. 
- Child goes next door to play computer games (look at pictures, watch movies). Some of the movies and pictures will be a little bit scary, others sad, others boring. 
- One of the games involves a loud annoying noise, we will adjust it for you. 
- You will also do some other games on paper and pencil - like puzzle and word games
- You will answer some questionnaires
- We will also measure your height, weight, and waist circumference. 
- We will take three biological samples: 
    - Hair - stress hormones
    - Saliva - microbiome 
    - Blood - immune - wear goggles
- Do you get sick or dizzy when you see blood or hurt yourself? 
- If we need to, can we prick two fingers?
- When you are done with all of that, you will get a big prize, then we will pay you and you will go home. 
- You will get $45 for the work you put in today.

### Things you will do at home

<h4>Child</h4>

- Poop sample - microbiome
- Stool scale
- Memory game - to see what you remember from lab.

<h4>Parent</h4>

- 24 hour food recall

When you complete the poop sample and the games at home, we will pay you another $20 in the form of a giftcard. 

### Things to know

You are a volunteer, which means that you do not have to do anything, or say anything that makes you uncomfortable. We would like you to try everything you can, and to do your best, but if there are things you absolutely do not want to do, just tell us, that is o.k.

We keep your participation confidential - ID number. 

We want you to come in again in the future, so we will ask for some information so we can contact you in the future. 

*Sign consent/assent forms including DBS form and Contact Sheet*

-----------------

## Recruitment

### Pre-Screening

 1. Check if participant is in Recruitment Database
     - If not, add them to the Recruitment Database
 3. Check if participant is in ID Drive
    - If yes, check if they have a Screener ID
    - If not, assign them a Screener ID once contact has been established based on the next available Screener ID # in REDCap and proceed with screening
    - If yes, proceed with screening under existing Screener ID in REDCap

### Screening

1. To screen a new participant click “Add / Edit Records”
2.  Click to enter a new Subject ID
    - Make sure Arm 1: Recruitment is selected
3. Type “SMBB#” (Screener ID) to create a record and hit “Enter”
    - Make sure to link the participants Screener ID and their name on the **ID Drive ONLY**
    - Before creating a new record, be sure to check the ID Drive to see if the participant already has an existing Screener ID
    - If a record exists, add a new instance of the screen instead of creating a new record

4. The screening arm contains two parts
    - The screen
    - The wave1_status
        - The wave1_status is to be updated after the first and each subsequent contact

5. Click on the radio button in the “screen” row to screen the participant
6. Click “Now” to enter today’s date and time
7. Select the appropriate choice to start the phone call and follow the skip logic.
8. Follow the skip logic to the end.
    - For items without a text field, write the information down in the Recruitment database (This identifying information cannot be on REDCap)
9. Once done, select “Complete” and “Save & Exit Form”
    - The screen can be entered multiple times - for instance if there are multiple phone calls or contacts
    - It is important to keep a record of all instances of contact

10. Click the screen_status radio button
11. Select the appropriate option
     - Contact - Participant needs to be re-contacted (add Recruitment Database & ID Drive)
     - Ineligible - Participant not eligible for study
     - To Enroll - Participant to enroll (need to create subject ID, enter subject info, schedule participant, add to Recruitment Database, add to ID Drive)
     - Enrolled - Participant has been enrolled (all above have been completed)
     - To Remove - Participant wants to be removed
12. Be sure to update the screen status after each contact
     - After 3 contacts (with no response) - review (time of day, contact method, etc.)
13. If enrolled, proceed to pre-session checklist in the participant log


### Other Screening Information

<h4>Accessing Lists</h4>

To find out where participants are in the recruitment process, there are several lists. 


1. Click on “Record Status Dashboard”
2. Participants who have been enrolled will be listed in the Enrollment - Wave 1 list
3. Participants in the process of recruitment will be listed in one of the 4 Recruitment lists
    - *These lists are populated based on the individuals “Screen Status” so be sure to update after each contact!

<h4>List Types</h4>

- Contact - List of individuals who need to be contacted or re-contacted (also includes waitlist)
- Ineligible - Participants are ineligible but interested
- To Enroll - Participants who have been screened and are eligible to enroll
- To Remove - Participants who were not interested in being contacted for this or future research

## Addressing Concerns

If a parent has a concern about the study before the session, send the email template: 

- [MBB - CONCERNS]

----------------
