# Wave 1 Online

## Checklists Online

-----------

### Checklist - Initial Online

**Calling participants from REDCap**

- Participants can be considered "lost to follow up" if they meet all of the following criteria:
  - Researcher has tried to contact individual at different times of day.
  - Researcher has used at least 2 different approaches (e.g. email and phone), UNLESS only 1 form of contact has been given, in which case participant should fully meet all other criteria.
  - Person has been contact at least 4 times. 
  - Situation is NOT considered "phone tag" (a participant calls and lab member returns call but keeps missing one another- this shows participant may still be interested, therefore number of contact and lack of response may not be due to lack of interest. Participants in "phone tag" situation should stay on contact list).

**Waitlist criteria**

- This regards the “out of town” option on the wave1_Status on REDCap
- Should include:
  - any participants here live outside of LA, and won’t be coming back to LA (e.g. did not relocate just for COVID-19 pandemic purposes)
  - participants whose age tally exceed 10, the target collection number for each age group in our age range. Refer to the [Participant Tally](https://ucla.app.box.com/file/724688028024) for reference. 

**PLEASE NOTE: Participants who have not aged out yet, or who are not free at the moment yet, OR live outside the US but plan to come back as soon as the pandemic is over should all still be kept on the contact log and just have a future recontact date. We only want to put people who are going on our  “out of town” waitlist (like a plan B, only contact if necessary)!**

We will only refer to the waitlist if (1) we will be behind on recruitment for Wave 1 and will need to just schedule people who we know cannot come back for future waves to complete data collection or (2) we will be behind on recruitment for Wave 1 and will need to just schedule people who are anywhere within our age range, rather than targeted numbers by age to complete data collection (3) we have to stay in the pandemic and all future waves will be remote. 

**Important Reminders**

  **Screening**
  
  - Check participant tally before screening to know if we would be scheduling or waitlisting if they qualify 
  - When answering the call ask who you are speaking with ( so we know if it’s a parent or teen)
  - If a potential participant is not of age then put their recontact to future around the time they would qualify 
  - If screening a family with multiple children each child has to be screened with their own smbb
    - Oldest child gets next available smbb number just like the mbb number protocol 
    - Only exception is if we only knew about younger child then during screening mentions they have another child that wants to participate.
  - Triple check you write down the address correctly for participants ( repeat it back to them / spell it out) 
  - Do not run session until you are 100% sure they are eligible. If unsure of a criteria verify it before session. 

  **Calendar**
  
  - Put the W1 for wave one ( e.g. S1 W1 ) on session events
  - For reminder emails put Status: Incomplete in description
  - For Session 1 Reminder 1 call event put “Only if no email response” in the description and then status: Incomplete
  - Whenever you complete a reminder event mark it as complete and update the MBB participant log 
  
  **Emails to participant**
  
  - Move potential participant email to “Added” tab of MBB once you add them to the participant database 
  - All emails to a participant should be in the same thread 
    - The thread we initially contacted them at should be the one we send the session confirmation to   - **Remember that email templates need to be edited**(e.g. there are no written responses in wave 2 so that chunk should be deleted, there is no ASA in wave 1 so that should be deleted in wave 1, etc.)
  - The easiest way to not forget steps is to do all “ session has just been scheduled” tasks based on the MBB log 
  - Make sure you are sending the correct reminder email - S1 R2 is the one with the researcher card 
  
  **Confirming sessions**
  
  - Do not put as “ confirmed session” on MBB log unless we got verbal confirmation / email confirmation
  - If called and no answer leave a note on the calendar event saying was not able to verbally confirm & also put into SRA chat 
  
  **REDCap** 
  
  - Log into REDCap with your own account to avoid confusion and for easier identification of who screened each smbb participant
  - After contacting someone change the Wave status “date to recontact”  to one week from the current date ( can be two weeks if it’s someone that hasn’t responded in long time)
  - When you schedule a new MBB participant change their SMBB “Wave 1 status” to enrolled 


**Scheduling and Confirmation**

- Schedule session 1 two weeks in advance from "package mailing day" (see package preparation in pre-session checklist)
- Schedule session 2 ~one week after session 1
- Ask Kristen to make Zoom link with scheduled session times and save to google calendar
- Send session 1 confirmation email (in templates)
   - Attach [Next Steps](https://ucla.app.box.com/file/665452959932), [Computer Zoom Download Instructions](https://ucla.app.box.com/file/680632734387)

**Enrollment**

- Create participant Box folder using MBB_template (delete blank README from newly created folder)
- Enroll participant in Wave 1 on REDCap
  - Go to “Add / Edit Records” of MBB
  - Make sure the tab is “Arm 2: wave 1”
  - Type in the next available MBB
  - * Be careful because any premature clicking makes a new ID*
- Fill participant instrument on REDCap
  - **Age should be the age of participant at the time of *Session 1* **
  - In notes section add the date and time of session
- Update [Participant Tally](https://ucla.app.box.com/file/724688028024)

**Calendar**

- Create MBB Session 1/2 calendar events (and invite researcher)
  - *MBBXXX WX- Online Session 1*
    - Add Lead and backup reseracher, MBB#, participant age, sex,whether Bio or els, and session time in the event decription 
  - *MBBXXX WX- Online Session 2*
    - Add Lead and backup reseracher, MBB#, participant age, sex,whether Bio or els, and session time in the event decription 
- Add participant to the weekly MBB mailing calendar event 
  - *MBB999 WX (Scheduled for 00/00/00) Sent: Incomplete*
- Create MBB Session 1/2 reminder calendar events
  - *MBBXXX WX- Session 1 Reminder 1 (email)* - 1 week prior
    - Add Status: Incomplete to the description
  - *MBBXXX WX- Session 1 Reminder 1 (call)*  - the day after Reminder 1 email
    - Add Status: Incomplete to the description
    - Add “Only if no email response”  to description
  - *MBBXXX WX- Session 1 Reminder 2 (email and call)* - 3 days prior
    - Add Status: Incomplete to the description
  - *MBBXXX WX- Session 2 Reminder 1 (email) * - 3 days before second session
    - Add Status: Incomplete to the description
  - *MBBXXX WX- Session 2 Reminder 2 (call)* - 2 days before second session
    - Add Status: Incomplete to the description
- Create MBB Home Session reminder calendar events
  - *MBBXXX WX- Home Session Reminder 1 (email)* - 1 week after Session 2
    - Add Status: Incomplete to the description
  - *MBBXXX WX- Home Session Reminder 1 (call)* - 8 days after Session 2
    - Add Status: Incomplete to the description
  - *MBBXXX WX- Home Session Reminder 2 (email)* - 14 days after Session 2
    - Add Status: Incomplete to the description
  - *MBBXXX WX- Home Session Reminder 2 (call)* - 15 days after Session 2
    - Add Status: Incomplete to the description
    - Add * Only if package missing and have not been in contact with participant* to description
  
**Reminders**

NOTE: all template emails are in bablab gmail 

- Send *Session 1 Reminder 1* email
  - Update calendar event description to Status: Complete
  - Update MBB participant log 
  - Confirm package is received
- *Session 1 Reminder 1* call made
  - Update calendar event description to Status: Complete 
  - If no call made put “NA - responded via email”
  - Update MBB participant log - if NA put NA 
- Send *Session 1 Reminder 2* email & call
  - Update calendar event description to Status: Complete
  - Update MBB participant log
  - **Make a note on calendar whether they confirmed session**
  - **Send message to SRA chat whether participant confirmed and tag the researcher running the session**
  - Confirm package is received
- *Session 2 Reminder 1* email made
  - Update calendar event description to Status: Complete
  - Update MBB participant log
  - Confirm package is received
- *Session 2 Reminder 2* call made
  - Update calendar event description to Status: Complete
  - Update MBB participant log
  - **Send message to SRA chat whether participant confirmed and tag the researcher running the session**
- Confirm participant
  - Preferably by phone
  - Update calendar event description to Status: Complete
  - Update MBB participant log
  - Update *Session 1* calendar status
- Home Session Reminders
  - Check participant log to see what info is missing before sending home session reminder emails 
  - Check with Kristen if unsure what info is missing 
  - Make sure the list of “items needed” is tailored to that participant
  - Send written response links if it hasn’t been completed yet 
  - If package missing after home session email reminder 2:
    - send message to SRA chat that participant is still missing package
    - move on to home sess call 2 
    - next steps will be on a case by case basis
  

------------

### Checklist - Pre-Session 1

#### Package preparation: "magic box"
*(prepare and send from all scheduled participants in the last week, to be mailed 2 weeks prior to session)*

NOTE: Printing can be done in black and white. Labeling should be in the notation "MBB___ W_"

- Print [What is in this magic box and what goes back to the lab?]
- Print [Reward Board](https://ucla.app.box.com/file/668504120930) (plus gold star stickers)
- Print/Staple Parent Questionnaire Booklet (in this order)
  1. Parent Questionnaire Cover Page / Parent Proxy Intro 
  2. demographics
  3. financial
  4. covid_objective (parentproxy version)
  5. pedsql_gi_parentproxy
  6. pedsql_wb_parentproxy
  7. pedsql_f_parentproxy
  8. easy (revised)
  9. tesi (revised)
  10. cbcl (revised)
  11. cshq (revised)
  12. mb_metadata
  13. med_check
  14. pds
  15. dhws
  16. hpq
  17. parent_stress
  18. cssi (for children under 8)
  19. fci (only adopted)
  20. iai (only internationally adopted)
  21. Parent Self Intro 
  22. bdi
  23. covid_objective (parentself version)
- Print/Staple Session 1/Session 2 Booklet (in this order)
  1. Session 1 Cover page
  2. [Pleasant/Unpleasant Events Checklist](https://ucla.app.box.com/file/630327764749)
  3. [Height Measurement Instruction](https://ucla.app.box.com/file/698389151155)
  4. [Weight Measurement Instruction](https://ucla.app.box.com/file/698395394087)
  5. [Waist Measurement Instruction](https://ucla.app.box.com/file/698395657078)
  6. Saliva Sample Instructions Sheet
  7. [Hair Sample Instructions Sheet](https://ucla.app.box.com/file/685938821891)
  8. Session 2 Cover Page
  9. [Contact List](https://ucla.app.box.com/file/639652767665) and label with participant ID
  10. Stool Sample Instructions Sheet
  11. [Bristol Stool Scale](https://app.box.com/file/630326499609) and label with participant ID (MBB Specific Version)
- Prepare 1-2 sharpened pencils
- Prepare paper measuring tape (for waist and height measurements)
- Label 2 biohazard bags (with 2 cotton balls in each bag)
- Label 1 cardboard box (for samples)
- Label hair sample kit (aluminum foil 7"x7", painter's tape with "root end" labeled, 1 ziplock bag pre-labeled with participant ID & Wave)
- Include a hair comb and alligator clip
- Label stool sample collection kit (paper clip collection tube and toilet hat together)
- Insert purple gloves for stool sample
- Label saliva sample collection kit (collection tube)
- Insert MBB info card
- Attach FedEx slip to return mailer
- Label return mailer with "exempt human specimen" (in sharpie)
- Take picture of prepaid blue return mailer (marked with MBB number & Wave) and file in participant data folder on Box
- Insert all labeled items and forms for post-session in blue return mailer
- Insert all labeled items and forms for session itself in magic box
- Insert blue return mailer into study package
- Tape package closed and put BABLAB sticker on 
- Take a picture of study package with tracking information to file offline on researcher computer (NOT Box)
- Mail "Magic Box" package to participant

------------

#### Setup - 1 Hour Prior

- Open up Zoom link for Session 1
- Read "participant" information instrument on REDCap for notes section for any notes from the scheduler about child
- Open Slack and keep open for entirety of session for communication with the research team/Lab Manager
- If Lab Manager, assign all fellow researchers co-host. If SRA, ask Lab Manager to sign on to assign you Host or co-host.
- Pull up session scripts/protocol, Halloween training instructions, and Halloween Test instructions
- Send *Session 1 Links* email
  - NOTE: do not add Gorilla Code to LINKS email- code is their MBB # which cannot be paired with private information (participant's name/email)
- Activate the participant's ID on Gorilla; leave Gorilla open so researcher can track participant progress during behavioral task
- Prepare Session 1 checklist on REDCap
- Have the Participant's MBB and secondary MBB number on hand
- Preload the Consent/Assent picture slideshow on researcher computer
- Prepare biological sample kits for demonstration during session
   - hair sample, saliva sample, stool sample
- Ensure researcher's Zoom security settings are set for study session
- Have the following links ready to send to the Participant throughout the session: 
   - link to Consent on REDCap with codes ready
   - link to Child's Gorilla Game
   - link to child questionnaires on REDCap with codes ready

--------------

### Checklist - Session 1 

- Welcome & Introduction to Zoom (important features- chat)
- Session walk-through/package explanation
- Consent/Assent
- Parent-child observation (note recording via Zoom or participant recorded)
- If participant recorded, instruct participant how to upload to Box
- Explain Questionnaires Parent Proxy or Parent self on second device if available (for parent to complete during Halloween training, Halloween test, and Child Questionnaires)
- Halloween training
- Height
- Weight
- Waist circumference
- Halloween test
- Saliva sample
- Hair sample
- Child Questionnaires
- Stool Sample explanation
- Contact list explanation
- Qualitative parent and child free responses (optional) explanation
- Confirm mailing address for payment
- Confirm Session 2 time and date

-----------

### Checklist - Post-Session 1 

#### Notes

- Submit lab session checklist child
- Make note of issues to discuss (if needed) in Boxnote for next core meeting
- Update [Participant Tally](https://ucla.app.box.com/file/724688028024)
- Update Participant Log

#### Filing

- Transfer and rename Zoom recording to Box
- Download and copy behavioral task data (from Gorilla) to Gorilla data folder on Box

#### Reminders

NOTE: all template emails are in bablab gmail 

- *Session 2 Confirmation Email* sent with Zoom link, researcher info (right after Session 1)
- *Session 2 reminder 1* email sent with Zoom link (3 days before session 2)
- *Session 2 reminder 1* phone call made (2 days before Session 2)

------------

### Checklist - Pre-Session 2 

NOTE: all template emails are in bablab gmail 

- Send *Session 2 Links* email
- Open Gorilla to track participant progress
- Have the Participant’s MBB number on hand
- Open home session checklist on REDCap

------------

### Checklist - Session 2 

- Halloween test delay completed
- Fill in home session checklist on REDCap (halloween test delay information)
- Stool sample questions answered
- Wave 2 Interview
- Bristol Stool Scale reminder
- Contact information sheet reminder
- Walk through package to send back (check "mbb_online_package_checklists") for checklist of items participant needs to send back to the lab

------------

### Checklist - Post-Session 2 

- Save and submit home session checklist on REDCap (halloween test delay information)
- Update Participant Log
- Download and copy delayed behavioral task data (from Gorilla) to participant folder (raw)
- Send *Session 2 TO DO List* email from bablab gmail templates

--------

### Checklist - Final Online

#### Filing 

- Make low-res parent child interaction video and save on BABLab External Hard Drive
- Burn all audio and video (low res) files to CD and label/store CD in binder
- Make manila folder for participants to file all hard copies

#### Data Entry

- Enter online session checklist data to REDCap
- Enter height, weight, waist to REDCap

#### Reminders

NOTE: all template emails are in bablab gmail 

- *Home Session Reminder 1 Email* made
- *Home Session Reminder 1 phone call* made
- *Home Session Reminder 2 Email* made
- *Home Session Reminder 2 phone call* made

*After package has been received...*

#### Package confirmation

- Halloween test delay completed
- Hair sample received
- Saliva sample received
- Stool sample received
- Bristol Stool Scale data received
- Questionnaires received
- Contact information sheet received 

#### Data Entry

- Enter contact list information into recruitment database
- Scan and upload parentproxy questionnaires to Box
- Scan and upload parentself questionnaires to Box
- Enter questionnaires data to REDCap (parentproxy and parenself)
- Scan and upload Bristol Stool Scale to Box
- Enter Bristol Stool Scale data to REDCap
- Enter height/weight/waist to body measurements on REDCap

#### Filing

- File Consent/Assent forms in filing cabinet (consent manila folder)
- File contact list in filing cabinet (contact list manila folder)
- File Bristol Stool Scale in filing cabinet (participant folder)
- File questionnaires in filing cabinet if paper versions were sent (participant folder)

#### Sample Storage

- Label with PID and Wave and store stool sample (add data quality to REDCap)
- Label with PID and Wave and store saliva sample
- Label with PID and Wave and store hair sample
- Update sample storage log on Box (once all received)
- Upload all sample photos to Box

#### Data Quality

- Data quality check 1
- Data quality check 2
- Data review
- Data audit

#### Retention

- Prep report card
- Send report card email (in templates - attach report card)
- Update participant Wave 2 status

#### Reimbursement

- Mail payment with science kits
- Take a picture of tracking information and upload to Box
- Log participant payment in reimbursement log book
- Log participant payment in reimbursement spreadsheet
- Send payment confirmation email to participant

-----------------

### Checklist - No Show

- Delete session 2 & reminder calendar events from MBB calendar to avoid confusion
  - Session 2 reminder email
  - Session 2 reminder call
  - Session 2 session event 
  - Home session reminder 1 email
  - Home session reminder 1 call
  - Home session reminder 2 email
- Change REDCap status 
  - Go to “Default Dashboard” to access full list of SMBB numbers
  - Change REDCap SMBB wave 1 status from enrolled to default dashboard 
  - Note - MBB stays the same 
- Update [Participant Tally] (https://ucla.app.box.com/file/724688028024)
- Rescheduling steps 
  - Send No-show rescheduling email same day 
  - Add calendar event for reschedule call 1 (following day) 
  - Add calendar event for rescheduling email 2 (1 week after) 
  - Add calendar event for rescheduling call 2 (8 days later) 
  - Add calendar event for rescheduling email 3 (2 weeks after) 
  - Add calendar event for rescheduling call 3 (15 days later) 
- Add participant to “No-Show Tracking Sheet” 
  -Fill out information on tracking sheet for participant 



-----------------

