## Protocols - Session 2

### Protocol - Halloween Test Delay

[Once Zoom is Connected]

*Hello! Welcome back to Session 2!* [Ask how they are doing, and if they were able to try the Stool Sample collection. Answer any questions they have about their Home Session tasks (Stool sample, BSS sheet, Contact list)]

*So today we are just going to do one quick task and then I will walk you through how to close up package and send it back to us, then answer any questions you might have*

*OK! It is time to go back to our learning and memory section.*

[Give child instructions on Halloween Test] [Researcher to open up the [halloween_part_3](https://ucla.app.box.com/file/737558206552)]

*Ok [Child's name]- now we want to see how much of your trick-or-treating adventure you remember. You will see an instructions page like this first!*

*You will first be shown a candy or a toy and will be asked if you saw that candy or toy when you went trick-or-treating. This is where your memory kicks in!*

*Here are some examples of what you might see.*

*The next set of questions show the houses that you visited and asks what candy was found there and where it was located on the screen.*

*Here are examples of what this looks like!*

*We also want you to remember that this is not a test! Just try your best!*

*When you finish, all you have to do is let me know!*

[Researcher to stop sharing screen.]

*Can you please go back to the "Gorilla" website. If you still have the browser up that's great - please refresh the screen to continue. If not, you can go back to the same link as before and enter your MBB ID. Here you will be completing the second part of the computer game.*

[Wait for child to log back on]

If necessary - the link can be found [here](https://research.sc/participant/login/20451/publicid).

[Confirm that they are on the correct page] 

[Once confirmed, say] *Ok! Now you can get started!*


### Protocol - Mailing Package

*Next, I just want to check-in with you about mailing the package back to the lab.*

- Reference the Package Checklist which has a checklist for every item they need to send back to the lab
- Everything goes into the mailer with the FedEx sheet on top
- Double check that stool and saliva sample are correctly packed (tube in biohazard bag with cotton balls, inside rigid white box)
- Drop off at any FedEx location or post box

### Protocol - Payment

- Explain that once the return mailer has been received to the lab after the second session, we will send payment through the mail along with a few educational science kits
- Explain that they should expect an email from us when we send the package, and if they haven't heard from us one week after we have sent the package, call to check-in about the payment

### Protocol - Wave 2 Interview

- Researcher to open up REDCap Home Session Checklist and read script about Wave 2 Interview
- Researcher to take notes on parent response

*Usually we do these sessions in person, and for second wave of this study in one year from now, we'd love to have you come in person! Who knows what world will look like then, but I'd still like to ask some questions to gauge at a bare minimum what you would need to feel comfortable with coming back into the lab.*

### Protocol - Testimonials
*We wanted to know if you are interested in providing a testimonial for our website about your experience participating in our Mind, Brain, and Body study. If you choose to provide a testimonial we will post it on our website. We would also include first name and your child's first name and age if you grant us permission to do so. Is that something you would be interested in?*

If yes: *Great, thank you for your interest in sharing your experience! Please send us the testimonial via email and indicate whether we can include your names. It can also be anonymous if you would prefer that.* Send written request for testimonial after ending session. 

If no: *No problem at all, thank you for participating in our study!*

-----------

## Protocols - Post-Session 2 


### Protocol - Downloading the Gorilla delay test data

1. Login to Gorilla and navigate to the experiment's data tab.
2. If data is up to date, you can go ahead and click download. NOTE: ENSURE you are on the correct VERSION PICKER. You can double check your participant's version number in the "recruitment" tab where the participant lives. Change the version picker to the correct version for that participant. 

3. If data is not up to date, scroll down and click the necessary options, then click "Regenerate Data".
4. You will see a wait screen as it generates.
5. After a few minutes click into "Manage experiment data" again and download. 
6. Unzip the file to your desktop.
7. Open the correct delay test file and check that the participant's data is all there. NOTE: can check the participant's specific nodes to see the code of their halloween test delay, which will tell you which file their data is located in.
8. Save this file in the Gorilla data folder on Box as "month_day_year.csv"

### Protocol - Session 2 TO DO List Email

- Fill in templated email with all leftover tasks for participant to complete
- Add links to REDCap for their optional qualitative responses
- Refrain from sending this email if they ONLY have qualitative responses left to do- participants will get 2+ emails through our "home reminder" system. This email is designed more for participants who have not done the stool sample yet, or still have outstanding tasks from Session 1 that we'd like to remind them about immediately/are time sensitive.


### Protocol - If participant had feedback to give



- If participant provided feedback on their experience or had comments to give us make a note of it on the "other notes" section of the session 1 checklist on REDCap. Also send a message to lab manager with an overview of feedback provided and whether it is feedback we should consider for the future. 

