## W2 Protocols - Session 1   


### W2 Protocol - Welcome & Zoom Introduction 


[ONCE ZOOM IS CONNECTED] 


*Hi! Thank you so much for joining us today! We are so looking forward to today’s session with you. * 

*Our session today should take around 2 hours long. In addition to what we do here today, there will be a follow up zoom appointment with us one week from now. At that appointment, we will reconnect on a second Zoom call in which your child will log on for 15 minutes and complete a computer game.* 

*I’ll be sending a message to the chat box just to make sure everything is working. You may already know this, but you can also display your camera so that it is in gallery view or speaker view in the top right corner. I think it might be best for you to do speaker view so it will feel more like we are in the room together!* 

*If for any reason, we lose each other over Zoom, the connection seems to be bad, or one of us freezes, lets leave the session and try to reconnect on the same link again. If I am frozen- feel free to leave and come back. If you leave and I don’t see you come back, I will try to give you a phone call!* 

*How does that sound? Do you have any questions?* 

[If no, say] *Great! Let’s switch gears and talk a little bit about what we are going to do today. Let me just pull up a little presentation we have got!*  

  

Researcher to open up the [MBB_W2_Consent_Script_Presentation](https://app.box.com/file/777489326925)] 

  

### W2 Protocol - Consent & Assent Online 


*Before we begin, I just wanted to let you know that in this study, we ask a lot of questions about family life and tough things that might have happened to kids. We are going to ask these questions to you and we ask a couple to your children as well, we just want to let you know that it is in our protocol to make sure everyone is safe, so if you or your child reveals to us that you're at current risk of harm or if you're at risk of harming someone else, then we will follow up with you and make sure everything is okay. If it is not, then we will take some steps to make sure that we keep everyone safe.*  


*First thing we are going to do is go over what is on the consent and assent forms. (These are the attached documents we sent you in the emails leading up to this session.) We will walk through, in a little bit more detail, all of the things we will be doing during today’s session.* 

  

*During today’s online session we are going to be doing some interactive things. First, we are going to have you and your parent sit and talk about some not so fun things and some fun things while on ZOOM. This conversation will be recorded but we will not be watching or listening in* 


*Next, we are going to have you play a game on the computer. In this game, you will be looking at pictures. Some of the pictures will be a bit scary, some sad, others a bit boring. While you are playing this game, your parent will stay with you in the room but will be working on some surveys to fill out.* 


*After the game is over, your parent [NAME] will help measure your height, weight, and waist circumference.* 


*You will also be answering some surveys (for children) with the researcher OR (for teens) on your own.* 

  

*Lastly for today, your parent will help take two biological samples during this session.* 

  

1. One is the hair sample which helps measure hormones that everyone has in their hair 

2. Two is the split sample which helps tell us learn a little bit more about your microbiome 

   - Do you know what a microbiome is? 

   - A microbiome is all the little bacteria that live inside your mouth. Everyone has these, they are healthy! We just want to know what kind and how many of each there are. 

  

*For helping us out in today’s session, you will be getting $30 for the work you put in! After this online session is over, we’ll ask you to do four more things in the second session:* 

  

*1. One is the Child poop sample – this helps us learn a bit more about your microbiome* 

  *- There are also little bacteria that live in your tummy! Everyone has these and we want to know more about them.* 

*2. Two is filling out the stool scale – this is a short scale that gives a description of your sample*

*3. Three is the computer memory game – this is when you will log back on with us via ZOOM in a week’s time to see what you remember from today’s session* 

*4. Four is the blood sample – this helps us look at immune markers which are very important for interpreting microbiome system because those systems talk to each other*

  

*Great! Do you have any questions for us about any of the samples* 


*Later in the year when things are safer, we would like you to invite you to come in for an optional brain scan using the MRI machine. You don't have to decide whether you want to do that now, but we just wanted to mention it here.*  


*You will receive $20 for doing the poop sample and $15 more for doing the blood sample!* 

  

*We will send the full payment of $65 ($30 for today’s session, $20 for the poop sample, and $15 for the blood sample) as soon as we receive the samples back through the mail.* 

  

*Here are some things to keep in mind:* 

  

*You are a volunteer in this study, which means you do not have to do anything, or say anything, that makes you uncomfortable. We would like you to try everything you can, and to do your best, but if there are things you absolutely do not want to do, just tells us, that is o.k.* 

  

*Another thing we want to remind you is that nothing you do today is a TEST!! We want you to try your best, but there is no "right" or "wrong" answers in anything you do today. We just want to learn about you!* 

  

*We will keep your participation confidential. You are given an ID number in order to keep your data confidential and separated from your name. Therefore, any identifying information (like your name, email, address, etc.) will be kept private and not paired with your data. We will also use a secondary ID number to save the videos with (since your faces are in it), which will help separate this from your name and the other data we collect form you. Only members of our research team will have access to your name and ID numbers.* 

  

*I will rename your "ZOOM Name" right now with your Secondary ID number, to prepare for the recordings we will take in our session today*  

  

[Researcher will rename the participant's name to "P" for participant. ] 

 

*Ok- I will now send you a link through the Zoom chat, which will open up a survey that allows you to virtually indicate your consent to participate in the study. Please feel free to take your time reading through the consent and assent forms now if you’d like. As I mentioned earlier, these are the documents we had previously sent you in the emails leading up to today's session.* 

[Bottom of consent form has the information about the arm poke, make sure to mention that and note whether they consent] 

[Then once they are done reading through] 

  

*All set and any questions?* 

  

[IF NO,] *Please click to indicate yours and your child's consent/assent and verbally let us know each of the items you have consented/not consented for, so we can adjust the session in case there is something you/your child may not feel up for today!* 

  

*You may press submit once you are finished to “send in the form.”* 

  

Researcher to grab magic box. 

  

*Once you are all set with that, we’d like you for to grab the magic box we sent you in the mail. This contains everything you will need for today’s session and what you will do as apart of Session 2 as well.* 

  

*If you haven't already done so, please open the magic box up. The magic box should contain a sheet of paper at the top which details all of the contents, but we will let you know when you need to take each item out of the box. Please set aside the magic box for now but keep the materials near you as we may need to access materials from the magic box throughout today’s session!* 

  

*What you can pull out now and use throughout the session is the Reward Board and Gold Star Stickers. Use this reward board to track all the steps you accomplish today! Each space is like each task for the session. Once you complete the task you can put a gold star on the space!* 

  

*Are you ready to get started on the session? Great, lets dive in!* 

  

----------------- 

  

### W2 Protocol - Parent Child Observation Online 

  

The parent and child will be seated together in view on the Zoom camera. During that time they will be filmed while solving a conflict, and then again while discussing a pleasant event. The conflict event will always go first, followed by the pleasant event. We did this to ensure that the parents were not thinking of the negative interaction upon answering the questionnaires about their child, which they did immediately after the observation interaction. 

  

[RESEARCHER SHOULD ASSESS VOLUME. If participant volume is too low, recording will not pick it up. Ensure that volume is at an appropriate frequency before proceeding to PC interaction recordings.] 

  

[RESEARCHER SHOULD CHANGE TO SPEAKER VIEW. Participants should be in speaker view so recording will enlarge the parent and child for behavior analysis.] 

  

Step 1: 

The researcher will ask the parent to find the [Pleasant/Unpleasant Events Checklist](https://ucla.app.box.com/file/630327764749) piece of paper from their session package. 

  

*Researcher: So the first thing we will have you pull out of the magic box is the paper packet titled "Online Session Booklet." You can flip to the page that says "Issues Checklist."* 

  

Researcher will wait for the participant to find the Online Session Booklet and flip to the correct page. 

  

*Researcher: Next we are going to take some film of you while you discuss something that's hard and try to resolve it. On this piece of paper (Issues Checklist) is a list of things that parents and children sometimes have disagreements about. We will give you a moment to read the list and think about some that you would like to discuss together. Then after about one minute, you will start discussing the things you have selected and try to resolve them. You do not need to tell us what you chose to discuss, and it does not matter if you chose something from this list, or decide to choose something else. Please choose something you can try to resolve (not an emotionally charged topic that would be difficult to discuss together right now). And we want you to remember- this is not a test and there are no right or wrong things to say!* 

  

*I am going to turn off my camera and mute myself to be out of the recording, and I will also step out of the room and will not be listening in. I will come back in and let you know when the six minutes are all done!* 

  

*When you are ready, I will begin the recording and give you a total of 6 minutes- one minute or so to choose, then five minutes to discuss! Are you ready?* 

  

Step 2:  

- Researcher will ensure Zoom security settings are set up for the video. 

- Parent and child will be situated side-by-side in view on the Zoom camera. 

-Researcher will press record on the Zoom application. Wait to hear the audio Zoom confirmation *"this meeting is now being recorded"* and view recording in progress at top left of screen to ensure recording is live. 

- Researcher set timer for 6 minutes 

  

Step 3: 

- Researcher will mute themselves on Zoom and turn off their camera, and step out of the room. 

- Researcher will start timer for 6 minutes. At the end of 6 minutes, reenter camera view and unmute themselves. 

  

[After 6 minutes have passed, say] *Thank you for taking the time to discuss something difficult. Next we are going to take some film of you talking about something nice. You can flip to the page that says "Pleasant Events Checklist." On your "Pleasant Events Checklist" is a list of fun things that parents and children sometimes do together. I will give you a moment to read the list and pick something that you would like to plan to do together. Then after about one minute, you will start discussing the things you have selected and try to plan them. Again, you do not need to tell us what you chose to discuss, and it does not matter if you choose something from this list, or decide to choose something else. When you are ready, I will start the recording and then give you a minute to choose and five minutes to discuss!* 

  

*I will be give you six minutes in total, one minute to choose and 5 minutes to discuss- remember, try to plan whatever fun thing you talk about during those five minutes. After, I will come back into the video call and give you further instructions. Do you have any questions?* 

  

If no questions, proceed. 

  

Step 5: 

- Researcher will start timer for 6 minutes.  

  

Step 6: 

- After six minutes, researcher reenters the room and back into camera view, turns up volume on the computer, and stops the recording on Zoom. You will view this notification in the upper right hand corner that states the recorded file will be converted to mp4 once the meeting ends.  Move the child/adolescent and parent onto the next task in the session, as the video will not be saved until after the session is complete. 

  

**Please visit " Wave 1 Post-Online Session Protocols to view instructions on how to save the video recording.** 

  

  

----------------- 

  

### W2 Protocol - Halloween Training/Parent Questionnaires 

  

*Now we are done with the group activity. You can go ahead and take out your token board and gold star stickers, and stick one golden star on the first block, where the movie icon is!*  

  

*Next we will move on to some individual activities, where Mom/Dad will complete some surveys while you [Child's name] plays a computer game. The computer game is about your child’s learning and memory so it is important they don’t get help from you! We actually prefer you don't watch the screen so you don’t know which pictures they see. If you recall the example from our powerpoint at the beginning of this session, this will be the time that your child will see some pictures on the screen* 

*While your child is doing the game, you can get started on some parent surveys. So now I will ask you to reach into your Session Package and pull out the booklets titled "Parent Proxy Surveys" and “Parent Self Surveys” and a pencil to fill these out.* 


*We ask that you please fill the parent proxy surveys first and then parent self surveys. Some of these surveys are about your child and some of these surveys are about you. The game will take around 5-10 minutes and I will notify you when we are finished. You can go ahead and work on the surveys now while your child plays the game.* 
  

*I will now just give [Child's name] some instructions on the computer game. Let me share my screen so I can show you some examples!* 

  

Researcher to open up the [halloween_training](https://app.box.com/file/784726680410)] 

  

*Ok, [Child's name]- so in this computer game, you are going to go on a trick-or-treating adventure! First, you will be shown instructions that look just like this! The places you will be visiting are scenes that either have a toy or food. Your job is to do their best to remember what toy or food is with what scene.* 


*Here is an examples of what you might see* 


*In this picture, you are at a park and you got pancakes!*


*Here is another example.*


*In this picture, you are at a dark forest and you got a pogo stick!*


*Sometimes you will get food while other times you will get a toy, and sometimes you will be visiting a nice place while other times you will be visiting a scary one. Remember that the type of food or toy will vary and where it is found will differ. You will only be shown the photos for a few seconds, so do your best to memorize what food or toy goes with each place as quickly and as much as possible!* 

  

*We also want to make sure you are paying attention, so when you see this red triangle, we want you to hit the space bar (or click the square)!* 

  

*You will be reaching a halfway point where you can just click "continue"* 

  

*There are TWO PARTS to this game- we are only going to be doing PART 1 right now. So, it is super important that when you see the page that says you're finished with this part, PLEASE LET ME KNOW!!* 

  

[Researcher to stop sharing screen.] 

  

*So to get setup for the computer game, we will send you a link through the Zoom chat now. Let me know once the link has loaded.* 

  

[Researcher to send Gorilla task link through the chat, then wait for them to pull it up.] 

  

If necessary - the link can be found [here](https://research.sc/participant/login/39409/publicid). 

  

[Then, confirm they are on the right page] *You should be seeing a login screen that asks you to enter your primary participant ID screen.* 


*Ok! If you are ready to start, we will just have you or Mom/Dad click "Log in" on [Child's name]'s page, and you can get started!* 

  

Researcher to open [gorilla](https://gorilla.sc) to track participant progress. Click on my projects>MBB>MBB_wave_2>participants tab>scroll to their mbb number and click "view progress"] 

  

[RESEARCHER TO TAKE NOTES: PARENT BEHAVIOR DURING THE HALLOWEEN TRAINING] 

  

[If participants do not seem to check-in with researcher after ~15 minutes, ask if they have any questions] *Hi, just wanted to check-in and see if everything was going alright. Do you have any questions?* 

  

[Once you confirm on the "view progress" node that Halloween training is complete, say] *Great job! We have completed the second part of this session- you can go ahead and take out your token board and gold star stickers, and put another star on the second block!* 

  

----------------- 

  

### W2 Protocol - Height Online 

  

*Ok, for the next part of this session, we will have you (parent) pause on your surveys so you can help take some measurements from your child (height, weight, and waist). I will ask you to reach into your Magic Box and pull out the paper measuring tape.* 

   

*Please measure your child's height in inches.* 

  

[Researcher to note child's height on the session checklist REDCap.] 


----------------- 

  

### W2 Protocol - Weight Online 

  

*Next, we will do weight! Do you have a weight scale?* 

  

[If yes, say] *Please go and weigh your child, and return to the screen so we may record the number. You do not have to bring the scale to the camera!* [Researcher to note child's weight on the session checklist on REDCap.] 

  

[If no, say] *Can you please record an estimate of your child's weight?* [Researcher to note child's weight and check "approximated" on the session checklist on REDCap.] 


----------------- 

  

### W2 Protocol - Waist Measurement Online 

  

*Next, we will do the Waist measurement! You can go ahead and grab that paper measuring tape once again, and measure your child's waist at the belly button. You can do this over their t-shirt.* 


- Advise parent to hold tape measure at the child/adolescent's belly button and bring it around their waist, over their t-shirt 

- Make sure measuring tape is horizontal around the waist and even in the front and back 

- Keep the tape snug around the waist, but not compressing the skin 

- Have participant breathe in 

- Measure the participant’s waist just after they breathe out 


[Researcher to note child's waist on the session checklist on REDCap.] 

  

*Great! [Child's name]- We finished the height, weight, and waist measurements you can stick a star on the third block of your token board!* 

  
----------------- 

  

### W2 Protocol - Halloween "Test" Online 

  

*OK! It is time to go back to our learning and memory section.* 

  

[Give child instructions on Halloween Test] [Researcher to open up the [halloween_test](https://app.box.com/file/784728666967)] 

  

*Ok [Child's name]- now we want to see how much of your trick-or-treating adventure you remember. You will see an instructions page like this first!* 

  

*In part A you will be shown food or a toy and will be asked if you saw that food or toy when you went trick-or-treating. This is where your memory kicks in!* 

*Here are some examples of what you might see.* 

*In this case you are shown a pancake and asked did you see this while you were trick-or-treating*

*If you answer yes or no you will then be asked how sure are you that you saw that food or toy.*

*Part B shows the scenes that you visited and asks what food or toy was found there and where it was located on the screen.* 

*Here are examples of what this looks like!* 

*You will be shown a picture like this and asked which of the three choices you saw at that place.* 

*Then you will be asked where on the picture you saw the food or toy.*

*If you are not sure you remember where the toy or food was,that is completely okay! We just ask that you make your best guess!*

*Again, when you see the red triangle make sure you hit the space bar or click the square.*


*When you finish, all you have to do is let me know!* 

  

[Researcher to stop sharing screen.] 

  

*Can you please go back to the "Gorilla" website. If you still have the browser up that's great - please refresh the screen to continue. If not, you can go back to the same link as before and enter your MBB ID. Here you will be completing the second part of the computer game.* 

  

[Wait for child to log back on with primary participant ID] 

  

If necessary - the link can be found [here](https://research.sc/participant/login/39409/publicid). 

  

[Confirm that they are on the correct page] *If you left your browser up, you should see Part 2 of the game, if you had to click on the link again, you should see the same logon screen where you can enter your MBB ID. Do not click submit just yet!* 

  

[Once confirmed, let the parent know they can resume on their parent surveys during this time] *So just to reiterate, this next part is about your child’s learning and memory so it is important they don’t get help from you! We prefer you don't watch the screen so you don't know which pictures they see. While you wait for your child to complete their task for the next 15 minutes, you can get continue on your parent surveys. Once your child is finished, we can regroup!* 

  

*Ok! Now you can get started!* 

  

[RESEARCHER TO TAKE NOTES: PARENT BEHAVIOR DURING THE HALLOWEEN TEST] 

  

[If participants do not seem to check-in with researcher after ~15 minutes, ask if they have any questions] *Hi, just wanted to check-in and see if everything was going alright. Do you have any questions?* 

  

*[Child's name] great job! Now that we are done with the computer game, you can go ahead and put another star on your token board!* 

  

----------------- 

  

### W2 Protocol - Saliva Sample Online 

  

*Now, we will do some sample collections! The first one is the Spit Sample. As I mentioned earlier, you can flip to the instructions in your session booklet if you would like, but I will also walk you through it step-by-step! First, please grab your "spit tube" from the Magic Box. When you are ready, I will let you know what to do next!* 

  

*First, we just want to check-in to make sure you haven't had any food, water, drink, or gum in the last 30 minutes?* 

  

[If yes, say] *Ok- no worries, we just have to wait that time before we can collect the spit sample. Let's move on to the next task and come back to this later!* [Researcher to make note on home session checklist and return to this item later in the session.] 

  

[If no, proceed.] 

  

[Researcher to walk through Spit Sample.] 

  

*You can throw away all of the packaging once you have finished with the spit tube. All you need to return to us is the tube inside the biohazard bag with two cotton balls, inside the white cardboard box.* 

  

*We are now done with our spit collection! You can put another gold star on your token board!* 

  

- Researcher has saliva "spit tube" example for explanation to participants 

- Advise parents to have child/adolescent fill spit tube to indicated line 

- Do not count the bubbles at the top, ensure that the saliva reaches the line 

- Close the cap on the spit tube, to release the stabilizing solution and seal the sample 
  **Tell parent to close the cap very tightly and to shake the tube for 5 seconds**
  
- Put the sample in the biohazard bag with the two cotton balls inside 

- Put the biohazard bag with sample inside the rigid box and set aside for now 

  

----------------- 

  

### W2 Protocol - Hair Sample Online 

  

*Next up is the Hair Sample. Feel free to flip to the section on Hair Sample Collection in your session booklet, if Magic Box. When you are ready, I will walk you through it step-by-step!* 

  

#### Set Up Hair Sample Station  

  

- Ask parent to gather the following materials for their “hair-sample station”: 

  - 1 sheet of aluminum foil (provided) 

  - 1 small ziplock bag with participant ID (provided) 

  - Painter-tape (provided) 

  - 1 scissor (salon grade if they have) 

  - 1 rat-tail comb to thin out hair (provided) 

  - 2 alligator clips (provided) 

  

- Researcher set up the following materials (to help explain hair sample collection): 

  - 1 sheet of aluminum foil 

  - 1 small ziplock bag with participant ID 

  - 1 salon grade scissor 

  - 1 rattail comb 

  - Painter-tape 

  - 2 alligator curl clips 

  

  

#### Explanation 

  

- Refer to the instructions booklet included in the participant's magic box, found here: [hair_sample_collection_instructions](https://ucla.app.box.com/file/739671629603) 

- Tell the parent that you will go over it verbally with them BEFORE they should start collecting the sample.  

- Explain to both the child and parent that they will be collecting 30-50 strands of hair. The amount of hair to be collected is less hair than is lost in normal everyday-brushing from the back of the head. Show them the amount on your own head. 

- Inform them how the site for the sampling is hidden by the surrounding hair, therefore not visible after collection. 

- Explain how the sample is used to measure a hormone called cortisol that is present in the hair. 

- Show on the hair sample picture directions sheet the hair sample taken from the wig to illustrate the amount of hair that will be collected (30-50 strands). 

- Offer to show our hair sample collection video if the parent would like a more comprehensive visual.  

- After taking the sample, the parent will tape it to the aluminum foil. When doing this, it is VERY important to place the tape at least 3cm below the root end. To show the parent how long 3cm is, you can use the measuring tape provided, or tell them it is 1.5 inches (really closer to 4cm but better longer than shorter).  

- If hair kit included painters tape, ensure that at least 3 cm of root is above the painters tape, and that the tape does NOT cover the root. If hair is shorter than 3cm, instruct not to use the tape.  

- If hair kit included rubber band, ensure that rubber band is put on hair PRIOR to cutting. The rubber hand then helps secure the bunched hair in the foil after hair sample is taken.  

- When they are ready to package the hair sample, ensure that the foil does not fold at the root- this is a very sensitive area in which we are analyzing, and important not to damage! 

- When finished, hair sample should be put in the foil, in the ziploc bag, in the white box along with the other samples 

  

#### Hair Length 

  

- For short hair (less than or just above 3cm, i.e., too short to tape and still have 3cm usable), follow the Short-Hair Protocol below. 

- For longer hair (>3cm), follow the Longer-Hair Protocol below. 

- Ideally, hair samples should be at least 3cm long. If the hair is less than 1cm long, the sample cannot be used. 

  

**Short-Hair Protocol (1-3cm)- advise parent to:** 

  

- Select a portion of hair from the posterior vertex of the head (in line with ears is a good reference point).  

- Use the rattail comb to thin out the hair as much as possible, so that the parent is grasping a horizontal line of hair rather than a chunk.  

- Ensure that 30-50 strands are included in the portion being held.  

- Hold the loose hair tightly with index finger and thumb, and cut the hair along the part, as close to the scalp and as evenly as possible. 

- Place loose hairs in foil and fold it securely. Do NOT tape the hair to the foil. 

- Fold the foil without bending the hair, and ensure that the hair does not fall out of the foil. 

- Ensure the root-end on the aluminum foil is labeled and place it in the ziplock bag. 

- Ensure the ziplock bag is labeled with the participant’s ID and Wave. 

  

  

**Longer-Hair Protocol (>3 cm) - advise parent to:** 

  

- Take the comb and part the hair horizontally between the tips of the ears. 

- Take a clip to clip away the hair from the top of the parting. 

- Instruct the parent to grasp approx. 30-50 strands of hair under the hair that has been clipped up. 

- Use the rattail comb to thin out the hair as much as possible, so that the parent is grasping a horizontal line of hair rather than a chunk. After this step, ensure the parent is still grasping 30-50 strands.  

- Instruct the parent to cut the hair sample as close to the scalp as possible. 

- Attach the hair to the center of the aluminum foil by taping with painter’s tape - leave at least 3 cm of hair from the root end;  not cover the root end. 

- If parent does not know how much 3cm is, you can: say that they can measure it with the cm side of the measuring tape; if they know inches say it is about 1.5 inches (really closer to 4cm but better too long than too short); or offer to demonstrate based on the length of your own finger.  

- Place the hair inside the aluminum foil in the orientation indicated by the “root” written on the foil. 

- Fold the foil without bending the hair, and ensure that the hair does not fall out of the foil. 

- Place the folded foil in the ziplock bag. 

- Put the ziploc bag back in the magic box. 

  

  

*Now we are all done with the hair sample! You can go ahead and put another star on your token board!* 

  

Participants can also watch the video below: 

  

<iframe width="560" height="315" src="https://www.youtube.com/embed/9bR5Ma_qgw4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 

 

----------------- 

 

### W2 Protocol - Child Questionnaires Online 

  

#### IF THERE IS NOT ENOUGH TIME 

  

- If parents want to cut time, questionnaires can be done at another time, unless we have to read the surveys to the child through share-screen. (This applies to children who may have trouble reading, or are under the age of 8.) 

#### Before Starting Surveys 

*Next, we will move on to some Child Surveys. [Parent's name], for this next part we will be asking [child's name] some questions. Some of these questions might be about you, like about how supported she feels by mom/dad, or her life. We just want to make sure you don't provide parent help with this part! So if you prefer to step out of the room or if [child's name] wants to wear headphones while they answer that would be fine- if not, no worries!* 

[If yes, tell parents to work on parent questionnaires in the meantime. If they will leave the room, we will have the child call them when we are ready to regroup.] 

  
[If no, say this is alright and no worries. Parent can stay in room and work on parent questionnaires. Researcher to take note in session 1 checklist.] 


#### Recollected Surveys

[If there is a child recollected survey that needs to be administered **complete recollected surveys before doing rest of surveys**] 

*So these next surveys are ones that we noted were not completed during your first round of sessions with us. We wanted to include them here so that you may complete them if you would like. Of course, like everything else in the study these are optional so if you do not wish to provide this information, you may skip any question.* 

For recollected surveys we will be sharing screen and reading out the survey to the participant regardless of age. 

*In a moment, I am going to share my screen with you, so you can see the survey questions. I will then read out each question and answer choice and [child's name] can tell me your answer. Does that sound okay? * 

[Researcher to share screen] 
  
#### Wave 2 surveys 

[**Check how many surveys child has to do before either beginning with child surveys**]

#### Ages 8+ 


*I can either send you the link to the surveys and you fill them out on on your own or I can share my screen and read the questions out loud and you tell me what to respond.* 

  

[If the child wants to do it together, refer to instructions under AGES 6-7 below] 

  

[If the child wants to do it on their own, say] *I am going to send you a link through the Zoom chat, with a code you will input to access the survey! We are ALMOST done with the session, and these surveys will not take too long and I will be here if you have any questions! * 


[Confirm the child is on the right page before proceeding.] 


[To the child, say] *Let me know if anything is confusing, or if you have any questions! Let us know when you are all done!* 

  

 

[RESEARCHER TO TAKE NOTES: PARENT BEHAVIOR DURING THE CHILD QUESTIONNAIRES] 

  

#### Ages 6-7 


*In a moment, I am going to share my screen with you, so you can see the survey questions. I will then read out each question and answer choice and [child's name] can tell me your answer. Does that sound okay? * 

  

[RESEARCHER TO TAKE NOTES: PARENT BEHAVIOR DURING THE CHILD QUESTIONNAIRES] 


**END SURVEYS** 

*Now that we have finished all of your surveys, we can take out the token board and put a gold sticker down. Look, we are just about done!* 

  

[If parent departed the room or if child is wearing headphones, ask child to get parent back on screen or take headphones out so parent can rejoin the session.] 

  

----------------- 

  

### W2 Protocol – Explaining at home part of Session 2 

  

*At this time, I will now ask you to reach into your Magic Box and pull out your "Session 1 Booklet" out and flip to the cover page that says "Session 2 Booklet" so I can walk through the Session 2 instructions* 

  

[Wait for participant to retrieve Session 2 Booklet] 

  

- Stool Sample explanation & BSS sheet 

  - *In the "Session 2 booklet" there are instructions for the POOP Sample Collection and a short survey that should be filled out after the poop sample collection. There is a toilet hat and a gut kit in the session package, which are the two major materials you will need for this collection. *Please complete the poop sample collection and finish filing out the surveys this week so the package is ready to be sent out by our second session next week.* If you have any questions please reach out to us via email or give us a call.* 

  - [RESEARCHER THEN GIVE DETAILED POOP SAMPLE COLLECTION AND PACKAGING INSTRUCTION] 

- Contact list explanation 

  - *In a longitudinal study, information may change in time and we want to ensure we have a way to recontact you for the next wave if you are still interested in joining. The contact list is also in your Session 2 Booklet for you to fill out.* 

- ASA explanation 

   - *You will also be filling out one more survey called the ASA. The survey asks what your child’s general diet and what they generally eat which gives us information about their nutrition. If you fill it out we can also send you a nutrition report later if you are interested. It is entirely online and we will be sending you the link to the survey in an email shortly. The session 1 packet should have a page that says ASA. That page has the login information which you will use to access the survey. * 

- Sleep Diary explanation
  - *Your child will be filling out a sleep diary every day for the week between today's session and your session 2. The sleep diary is in the survey packet after the page that says Child self.* 
  
- Confirm Session 2 date and time 
  - *I just wanted to confirm that your current session 2 date and time still works for you. If the package is ready by the time of your session 2 are you able to drop it off that day or the next day?* 

- Payment 

  - Explain that once the return mailer has been received to the lab after the second session, we will send payment through the mail  


----------------- 

### W2 Protocol - Reporting

#### If an item on the "reporting" list is activated regarding potential Domestic Violence

- Researcher to chat with parent alone at the end of the session

[Researcher say] *So now that we have reached the end of the session [child's name] is all done! Congratulations and thanks so much for your hard work today [child's name]! Can we just grab [parent's name] for a chat real quick? This last part will just be between mom/dad and me.*

[Researcher to wait for child to leave]

*Awesome! So I just wanted to check-in about something with you real quick. Your child may have answered an item in our questionnaires related to [parents pushing or shoving each other/parents throwing things during fights]. It is in our protocol to just check-in and make sure everything is alright at home. UCLA has many resources we can connect you to if necessary. Is everything alright?*

**If yes, say** 

*Great! I am glad to hear it. Thanks for letting us know!* [Then proceed to thanking them for session and what to expect next week, etc.]

**If no, say**

*Are you in any immediate danger at the moment?* 

[If yes, say] *Thank you for letting me know. We are going to get in touch with our supervisor immediately. Please give me a moment to get in touch with her now.* Researcher will then slack and call Bridget immediately at 347-741-4103.

[If no, say] *Would you like us to connect you with some resources at UCLA?* If yes, *What sort of support would you be looking for? I'll take this to my supervisor and she will give you recommendations and give you a call!*

**If no, but you don't feel that everything is alright, say**

*Thank you for letting me know! I know this might be a bit difficult to talk about, and as we mentioned earlier in the session it is just part of our protocol to check-in, so our supervisor will be giving you a call some time in the next 24 hours to ask you some more questions.* Researcher to slack Bridget immediately and call her at 347-741-4103. 

#### If Suicidal Ideation arises...

Researcher to slack Bridget and call her immediately at 347-741-4103. Try to keep the person on the phone while Bridget gets in contact with the participant. If something happens and a participant mentions they may harm themselves/dropped off the call before you are able to reach Bridget, let Bridget know immediately and you will proceed together. 

------------