## Protocols - Session 2 

  

### Protocol - Halloween Test Delay 

  

[Once Zoom is Connected] 

  

*Hello! Welcome back to Session 2!* [Ask how they are doing, and if they were able to do the Stool Sample collection. Answer any questions they have about their Home Session tasks (Stool sample, BSS sheet, Contact list, ASA)] 

  

*So today we are just going to do one quick task, collect the blood sample ( if stool sample is done and they consented to blood sample), walk you through how to close up package and send it back to us, and then answer any questions you might have.* 

  

*OK! It is time to go back to our learning and memory section.* 

  

[Give child instructions on Halloween Test] [Researcher to open up the [halloween_part_3](https://app.box.com/file/784713950398)] 

  

*Ok [Child's name]- now we want to see how much of your trick-or-treating adventure you remember. You will see an instructions page like this first!* 

  

*You will first be shown food or a toy and will be asked if you saw that food or toy when you went trick-or-treating. This is where your memory kicks in!* 

  

*Here are some examples of what you might see.* 

  

*The next set of questions show the scenes that you visited and asks what food was found there and where it was located on the screen.* 

  

*Here are examples of what this looks like!* 

  

*We also want you to remember that this is not a test! Just try your best!* 

  

*When you finish, all you have to do is let me know!* 

  

[Researcher to stop sharing screen.] 

  

*So to get you setup for the computer game, we will send you a link through the Zoom chat now. Let me know once the link has loaded.* 

 

[Wait for child to log back on] 

  

If necessary - the link can be found [here](https://research.sc/participant/login/20451/publicid). 

  

[Confirm that they are on the correct page]  

  

[Once confirmed, say] *Ok! Now you can get started!* 

 

[Once finished with game] 

*[Child's name] great job! Now that we are done with the computer game.* 

 

### Protocol – Home Session Check In 

 

*I wanted to check in if you were able to do the poop sample, fill out the BSS and finish the parent_proxy and parent_self surveys?* 

 

If yes: *“ Great, thank you for completing all of that before our session today!* 

Proceed to doing blood sample.  

 

If no: *When do you think you will be able to finish? We will need to schedule a short 5 minute Zoom call within the next week so we can collect the blood sample. The sooner we are able to do that the better.* 

  - Schedule the third session within the next week at a time that works for you and the parent so blood sample can be collected. 
  
  - Emphasize that poop sample needs to collected before that session.  

 

### Protocol – Tasso Blood Sample Online 

 **[Verify they consented to blood sample during session 1]**

*Now we will be doing the blood sample. The kit comes with detailed instructions you can reference but I will also be going over with you right now. * 

  [Tasso Blood Sample Collection Video](https://vimeo.com/409226805)

1. Rub arm quickly and firmly just below the shoulder. Rub until it’s very warm to help your blood flow. 
2. Clean arm with alcohol pad. 

3. Open device pouch by pulling apart white and clear layers.  

4. Remove clear plastic cover over the red button. 

5. Peel paper tab behind the red button. Keep sample pod pointing down. 

6. Stick device to shoulder. Do not remove once it’s on. 

7. Press button quickly and firmly until it can’t go any farther. Wait two seconds then let go.  

8. Start a 5 minute timer. Keep arm at your side and watch dots fill. You won’t see blood right away. 
9. Peel off the clear film to expose the sample pod vent. 

10. Place device in the foil return bag and seal. Leave the moisture packs in the bag. 

11. **IMPORTANT: Write collection date and time on the inside flap of the box.** 
    - Researcher will also make a note of date and time sample was collected and put it in notes of REDCap checklist

12. Place bag in box and seal with the strip.  
 
- Note that if blood sample needs to be stored overnight ( if the package is not sent out on the day it is collected) please store it in a cool dry place not under direct sunlight.  

- If the package is ready to be sent back we will do the blood sample now and it needs to be sent out today / tomorrow at the latest 

- **It is important that the blood sample be sent back the day it is collected or day after so emphasize that it is important that the whole package get sent back asap after blood sample collection.** 

- Check that they write down date and time the blood sample was collected on the box the kit comes with 


### Protocol - Mailing Package 

  

*Next, I just want to check-in with you about mailing the package back to the lab.* 

  

- Reference the Package Checklist which has a checklist for every item they need to send back to the lab 

- Everything goes into the mailer with the FedEx sheet on top 

- Double check that stool and saliva sample are correctly packed (tube in biohazard bag with absorbent, inside rigid white box) 

- Double check that blood sample is correctly packed ( in biohazard bag with absorbent, inside rigid white box) 

- Drop off at any FedEx location or post box 

  

### Protocol - Payment 

  

- Explain that once the return mailer has been received to the lab after the second session, we will send payment through the mail  

- Explain that they should expect an email from us when we send the package, and if they haven't heard from us one week after we have sent the package, call to check-in about the payment 

### Protocol - Prize
- Before showing prize options check [Prize Log](https://app.box.com/file/734579293509) to verify what prizes are available. 
- Ask what prize they want. We will share screen and share the prize presentation. Whatever they choose researcher will make a note on checklist and lab manager will reference that when sending payment package. As prizes get claimed those choices will get crossed out.   

*You get to choose a prize for participating in the study! I am going to share my screen to show you the different prize options we have.*

[Researcher will open up [Prize Presentation](https://app.box.com/file/780536035674)]
 
- Once participant chooses prize researcher will make a note on the REDCap checklist. 

*Great, we will send your prize with the payment!* 


### Protocol - Testimonials 
 
[ Only ask if participants seem like a good candidate for a testimonial / had a particularly good experience particiapting.]

*We wanted to know if you are interested in providing a testimonial for our website about your experience participating in our Mind, Brain, and Body study. If you choose to provide a testimonial we will post it on our website. We would also include first name and your child's first name and age if you grant us permission to do so. Is that something you would be interested in?* 
 

If yes: *Great, thank you for your interest in sharing your experience! Please send us the testimonial via email and indicate whether we can include your names. It can also be anonymous if you would prefer that.* 


If no: *No problem at all, thank you for participating in our study!* 
 

----------- 

  

## Protocols - Post-Session 2  

  

  

### Protocol - Downloading the Gorilla delay test data 

  

1. Login to Gorilla and navigate to the experiment's data tab. 

2. If data is up to date, you can go ahead and click download. NOTE: ENSURE you are on the correct VERSION PICKER. You can double check your participant's version number in the "recruitment" tab where the participant lives. Change the version picker to the correct version for that participant.  

  

3. If data is not up to date, scroll down and click the necessary options, then click "Regenerate Data". 

4. You will see a wait screen as it generates. 

5. After a few minutes click into "Manage experiment data" again and download.  

6. Unzip the file to your desktop. 

7. Open the correct delay test file and check that the participant's data is all there. NOTE: can check the participant's specific nodes to see the code of their Halloween test delay, which will tell you which file their data is located in. 

8. Save this file in the Gorilla data folder on Box as "month_day_year.csv" 

  

### Protocol - Session 2 TO DO List Email 

  

- Fill in templated email with all leftover tasks for participant to complete 

- This email is designed more for participants who have not done the stool sample yet, or still have outstanding tasks from Session 1 that we'd like to remind them about immediately/are time sensitive. 

 

### Protocol – If blood sample not collected during session 2 
 

- Add to calendar the date and time scheduled to meet with participant again to collect blood sample. This is going to be a session 3 of sorts. 

- Change home session R1 email 1 calendar event date to one week from blood sample collection (session 3 )  

- Change home session R1 call calendar event date to 8 days after "session 3"  

- Change home session R2 email calendar event date to two weeks after "session 3"

- Change home session R2 call calendar event date to 15 days after "session 3"


### Protocol - If participant had feedback to give

- If participant provided feedback on their experience or had comments to give us make a note of it on the "other notes" section of the session 1 checklist on REDCap. Also send a message to lab manager with an overview of feedback provided and whether it is feedback we should consider for the future. 

